# Generated by Django 4.0.1 on 2022-01-30 13:19

from django.db import migrations, models
#first ma model ma class Product(models.Model): garera model banauane ani-
#py manage.py migrate garney ani-
#py manage.py makemigrations ra py manage.py migrate garepaxi yo file generatre hunxa

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
